version: '2'
services:
    sales_benefit-app:
        image: sales_benefit
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sales_benefit-postgresql:5432/sales_benefit
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sales_benefit-postgresql:
        extends:
            file: postgresql.yml
            service: sales_benefit-postgresql
